version: 2
jobs:
   build:
     docker:
       - image: circleci/openjdk:8-jdk-browsers
     steps:
       - checkout
       - run: echo "running tests"
test:
  post:
    - mkdir -p $CIRCLE_TEST_REPORTS/junit/
    - find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
